fix<ftpd> it has been used in all the branches i'm working on
addgroup: group 'ftpgroup' in use
PermissionError: [Errno 13] Permission denied: '/app/create_user.sh'